---
# Replace the values in '<>' with your bot data.

# Used to generate a bearer token for requesting data from Twitch.
access_token: <access token>
client_id: <bot client id>
eventsub_secret: <bot eventsub secret>
oauth_token: <bot oauth token>
refresh: <refresh token>
secret: <app secret>

# Used to authenticate the bot to IRC.
irc_oauth: <irc oauth token>

# Discord authentication
discord_token: <access token>

# OBS authentication
obs_websockets_pass: <obs password>
