CREATE TABLE IF NOT EXISTS users (
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
username TEXT NOT NULL,
user_id INTEGER NOT NULL,
is_mod INTEGER DEFAULT 0,
is_regular INTEGER DEFAULT 0,
is_banned INTEGER DEFAULT 0,
ban_until TEXT NOT NULL DEFAULT "1970-01-01 00:00:00",
time_watched INTEGER DEFAULT 0,
messages_sent_session INTEGER DEFAULT 0,
messages_sent_total INTEGER DEFAULT 0,
first_join_time TEXT DEFAULT "1970-01-01 00:00:00",
last_join_time TEXT DEFAULT "1970-01-01 00:00:00",
last_leave_time TEXT DEFAULT "1970-01-01 00:00:00",
announce INTEGER DEFAULT 0,
points INTEGER DEFAULT 0,
loyalty_points INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS users_index ON users(username, user_id);
CREATE TABLE IF NOT EXISTS viewer_stats (
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
date TEXT NOT NULL,
time TEXT NOT NULL,
viewer_count INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS stream_stats (
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
bits INTEGER NOT NULL DEFAULT 0,
chatters INTEGER NOT NULL DEFAULT 0,
followers INTEGER NOT NULL DEFAULT 0,
messages INTEGER NOT NULL DEFAULT 0,
raids INTEGER NOT NULL DEFAULT 0,
rewards INTEGER NOT NULL DEFAULT 0,
stream_end TEXT NOT NULL,
stream_start TEXT NOT NULL,
subscribers INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS stream_events (
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
stream_end TEXT NOT NULL,
stream_start TEXT NOT NULL,
usernames TEXT
);
